---
# vars file for roles/update_packages---
packages: "{{ general_packages | union(lookup('vars', ( FAMILY | lower) + '_packages')) }}"  # yamllint disable-line rule:line-length

general_packages:
  - vim
  - xclip
  - solaar
  - tmux
  - vlc
  - qpdf
  - minicom
  - code
  - sublime-text
  - audacity
  - lutris
  - nmap
  - telnet
  - curl
  - calibre
  - syncthing
  - steam
  - vagrant
  - google-chrome-stable
  - qemu
  - qemu-kvm
  - dynamips
  - psutils
  - wireshark
  - yamllint
  - golang
  - xdotool
  - wmctrl
  - python3-netaddr
  - cmake
  - nodejs
  - pv
  - zsh
  - zsh-syntax-highlighting
  - brave-browser
  - deja-dup
  - ansible
  - ansible-lint
  - yamllint
  - yarnpkg
  - hugo
  - fd-find
  - cargo
  - luarocks
  - python3-neovim
  - ripgrep
  - clang

redhat_packages:
  - mediawriter
  - cascadia-code-fonts
  - mozilla-fira-mono-fonts
  - mozilla-fira-sans-fonts
  - powerline-fonts
  - fira-code-fonts
  - NetworkManager-openvpn
  - NetworkManager-openvpn-gnome
  - gnome-tweak-tool
  - wireshark-cli
  - tunctl
  - libvirt-client
  - gstreamer1-libav
  - gstreamer1-plugins-bad-freeworld
  - gnome-extensions-app
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-pop-shell
  - python3-pylint
  - python3-devel
  - ruby-devel
  - openssl-devel
  - fontawesome-fonts
  - spice-protocol
  - golang-x-tools-gopls
  - '@Development Tools'
  - '@Virtualization'

debian_packages:
  - fonts-cascadia-code
  - fonts-firacode
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - wireshark-common
  - wireshark-gtk
  - gstreamer1.0-libav
  - gstreamer1.0-plugins-bad
  - pylint
  - python3-dev
  - ruby-dev
  - virt-manager
  - ssh
  - npm
  - uml-utilities
  - podman
  - python3-venv
  - gopls

macos_packages:
  - ansible
  - zsh
  - go
  - fzf
  - neovim
  - tree
  - tmux
  - podman
  - tree-sitter
  - chezmoi

dnf_options:
  - option: fastestmirror
    value: true
  - option: deltarpm
    value: true
  - option: max_parallel_downloads
    value: 10
