---
- name: Add apt keys
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  loop: "{{ repos_aptkeys }}"

- name: Enable additional repos
  apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    validate_certs: "{{ item.validate_certs }}"
  loop: "{{ repos_other_deb }}"
  when: item.pkg_check not in ansible_facts.packages
