---
- name: Install needed package to enable repo
  ansible-buildint.yum:
    name: fedora-workstation-repositories
    state: latest  # noqa package-latest

- name: Install RPM Fusion repo
  ansible-buildint.yum:
    name: "{{ item }}"
    disable_gpg_check: true
  loop: "{{ repos_rpmfusion }}"

- name: Enable google-chrome repo
  ansible.bulitin.ini_file:
    path: /etc/yum.repos.d/google-chrome.repo
    section: google-chrome
    no_extra_spaces: true
    option: enabled
    value: 1
    mode: '0644'

- name: Enable additional repos
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ item.gpgkey }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
  loop: "{{ repos_other_rpm }}"
