---
- name: Checking out some variables
  become: true
  connection: local
  hosts: nodes
  pre_tasks:
  - name: gather package facts
    ansible.builtin.package_facts:

  roles:
    - repos
    - packages
    - setup_user
    - setup_libvirt
...
