---
- name: Checking out some variables
  become: false
  connection: local
  hosts: nodes
  vars:
    setup_user_name: pmartin

  pre_tasks:
  - name: gather package facts
    ansible.builtin.package_facts:

  roles:
    - name: repos
      become: true
    - name: packages
      become: true
    - setup_user
    - dotfiles
    - setup_zsh
    - name: setup_libvirt
      become: true

  tasks:
    - name: Print out reboot var
      debug:
        var: needs_reboot.stdout
...
