---
- name: Checking out some variables
  become: true
  connection: local
  hosts: nodes
  vars:
    setup_user_name: pmartin

  pre_tasks:
  - name: gather package facts
    ansible.builtin.package_facts:

  roles:
    - repos
    - packages
    - setup_user
    - dotfiles
    - setup_zsh
    - setup_libvirt

  tasks:
    - name: Print out reboot var
      debug:
        var: needs_reboot.stdout
...
