---
- name: Checking out some variables
  become: false
  connection: local
  hosts: nodes
  vars:
    setup_user_name: pmartin

  pre_tasks:
  - name: gather package facts
    ansible.builtin.package_facts:
    when: FAMILY != 'MacOS'

  roles:
    - name: repos
      become: true
      when: FAMILY != 'MacOS'
    - name: packages
      become: true
    - setup_user
      when: FAMILY != 'MacOS'
    - dotfiles
      when: FAMILY != 'MacOS'
    - setup_zsh
    - name: setup_libvirt
      become: true
      when: FAMILY != 'MacOS'

  tasks:
    - name: Print out reboot var
      debug:
        var: needs_reboot.stdout
      when: FAMILY != 'MacOS'
...
