---
- name: Setting up after a fresh install
  hosts: nodes
  connection: local
  become: false
  vars:
    setup_user_name: 'pmartin'
    setup_user_group: '{{(FAMILY != "MacOS") | ternary(setup_user_name, "staff")}}'

  pre_tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
      when: FAMILY != 'MacOS'

    - name: Get user stat
      ansible.builtin.user:
        name: '{{ setup_user_name }}'
      check_mode: true
      register: user_stat

    - name: Display user_stat
      ansible.builtin.set_fact:
        user_home: '{{ user_stat.home }}'

  roles:
    - role: repos
      become: true
      when: FAMILY != 'MacOS'
    - role: packages
      become: true
    - role: setup_user
      become: true
    - role: setup_zsh
    - role: setup_libvirt
      become: true
      when: FAMILY != 'MacOS'

  tasks:
    - name: Print out reboot var
      ansible.builtin.debug:
        var: needs_reboot.stdout
      when: FAMILY != 'MacOS'
...
