---
# tasks file for roles/update_packages
- name: Update packages on system
  ansible.builtin.apt:
    name: "*"
    state: latest  # noqa package-latest
    update_cache: true

- name: Install some needed packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Services that need to be started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - ssh
...
