---
- name: Update dnf.conf
  community.general.ini_file:
    path: "/etc/dnf/dnf.conf"
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0644'
  loop: "{{ dnf_options }}"

- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest  # noqa package-latest
  register: needs_reboot_pkgs

- name: Install some needed packages with dnf
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  notify: Restart sshd
...
