---
# tasks file for roles/update_packages
- name: Update packages on system
  dnf:
    name: "*"
    state: latest  # noqa package-latest

- name: Install some needed packages with dnf
  dnf:
    name: "{{ packages }}"
    state: present

- name: Add some flatpak remotes
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install some needed packages with flatpak
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ flat_packages }}"

- name: Services that need to be started
  service:
    name: "{{ item }}"
    state: started
    enabled: True  # noqa truthy
  loop:
    - sshd
