---
repos_rpmfusion:
  - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
  - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

other_rpm_repos:
  - name: Visual-Studio-Code
    description: Visual-Studio-code-repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: true
    gpgcheck: true
  - name: Sublime-Text
    description: Sublime-Text-repo
    baseurl: https://download.sublimetext.com/rpm/stable/x86_64
    gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    enabled: true
    gpgcheck: true
  - name: Brave-Browser
    description: Brave-Browser-reimagined
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    enabled: true
    gpgcheck: true

other_deb_repos:
  - filename: visual-studio-code
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    validate_certs: false
  - filename: google-chrome
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    validate_certs: false
  - filename: sublime-text
    repo: deb [arch=amd64] https://download.sublimetext.com/ apt/stable/
    state: present
    validate_certs: false
  - filename: gns3
    repo: ppa:gns3/ppa
    state: present
    validate_certs: false
  - filename: brave-browser
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
    validate_certs: false

aptkeys:
  - url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  - url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  - url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  - url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    state: present
