---
# tasks file for roles/setup_user
- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
    state: present
  loop: "{{ new_groups }}"
  when: FAMILY != 'MacOS'

- name: Configure user
  ansible.builtin.user:
    name: "{{ setup_user_name }}"
    groups: "{{ (FAMILY != 'MacOS') | ternary(user_groups, omit) }}"
    append: "{{ (FAMILY != 'MacOS') | ternary(true, omit) }}"
    generate_ssh_key: true
    shell: /bin/zsh
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: "{{ setup_user_name }}"
    group: "{{ setup_user_group }}"
  loop: "{{ user_dirs }}"

- name: Install Neovim when OS not MacOS
  when: FAMILY != 'MacOS'
  block:
    - name: Find latest neovim release
      ansible.builtin.uri:
        url: https://api.github.com/repos/neovim/neovim/releases/latest
        return_content: true
      register: neovim_release

    - name: Get Neovim download URL
      ansible.builtin.set_fact:
        dl_url: "{{ neovim_release.json.assets | selectattr('name', 'equalto', 'nvim.appimage') | map(attribute='browser_download_url') | list }}"

    - name: Download nvim appimage
      changed_when: false
      ansible.builtin.get_url:
        url: "{{ dl_url[0] }}"
        dest: /tmp/nvim
        validate_certs: false
        mode: '0755'

    - name: Copy nvim
      ansible.builtin.copy:
        src: /tmp/nvim
        dest: /usr/local/bin/nvim
        mode: '0755'

    - name: Remove nvim in tmp dir
      changed_when: false
      ansible.builtin.file:
        name: /tmp/nvim
        state: absent

    - name: Remove annoying password prompt in FF with Yubikey
      ansible.builtin.lineinfile:
        path: /usr/share/p11-kit/modules/opensc.module
        state: present
        regexp: '^disable-in'
        line: 'disable-in: firefox thunderbird'
...
