---
# tasks file for roles/setup_user
- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
    state: present
  loop: "{{ new_groups }}"
  when: FAMILY != 'MacOS'

- name: Configure user
  ansible.builtin.user:
    name: "{{ setup_user_name }}"
    groups: "{{ (FAMILY != 'MacOS') | ternary(user_groups, omit) }}"
    append: "{{ (FAMILY != 'MacOS') | ternary(true, omit) }}"
    generate_ssh_key: true
    shell: /bin/zsh
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: "{{ setup_user_name }}"
    group: "{{ setup_user_group }}"
  loop: "{{ user_dirs }}"

- name: Remove annoying password prompt in FF with Yubikey
  ansible.builtin.lineinfile:
    path: /usr/share/p11-kit/modules/opensc.module
    state: present
    regexp: '^disable-in'
    line: 'disable-in: firefox thunderbird'
...
