---
- name: Find latest release
  ansible.builtin.uri:
    url: "{{ chezmoi_url }}"
    return_content: true
  register: chezmoi_release

- name: Get version number
  ansible.builtin.set_fact:
    version: "chezmoi_{{ chezmoi_release.json.name | replace('v', '') }}_linux_amd64.deb"

- name: Set download URL
  ansible.builtin.set_fact:
    chezmoi_dl_url: "{{ chezmoi_release.json.assets | selectattr('name', 'equalto', version) | map(attribute='browser_download_url') }}"

- name: Install the chezmoi deb
  ansible.builtin.apt:
    deb: "{{ chezmoi_dl_url[0] }}"
...
