---
nvim_appimage_path: "{{ user_home }}/.local/bin/nvim.appimage"

user_dirs:
  - "{{ user_home }}/.local/bin"
  - "{{ user_home }}/Documents/Projects"
  - "{{ user_home }}/Projects"

new_groups:
  - netdev
  - ubridge
user_groups:
  - ubridge
  - libvirt
  - dialout
  - netdev
