---
- name: Install Neovim when OS not MacOS
  when: FAMILY != 'MacOS'
  block:
    - name: Find latest neovim release
      ansible.builtin.uri:
        url: "{{ neovim_url }}"
        return_content: true
      register: neovim_release

    - name: Get Neovim download URL
      ansible.builtin.debug:
        var: neovim_release
        verbosity: 1

    - name: Get Neovim download URL
      ansible.builtin.set_fact:
        dl_url: "{{ neovim_release.json.assets | selectattr('name', 'equalto', 'nvim-linux-x86_64.appimage') | map(attribute='browser_download_url') | list }}"


    - name: Get Neovim download URL
      ansible.builtin.debug:
        var: dl_url
        verbosity: 1

    - name: Download nvim appimage
      changed_when: false
      ansible.builtin.get_url:
        url: "{{ dl_url[0] }}"
        dest: /tmp/nvim
        validate_certs: false
        mode: '0755'

    - name: Copy nvim
      ansible.builtin.copy:
        src: /tmp/nvim
        dest: /usr/local/bin/nvim
        mode: '0755'

    - name: Remove nvim in tmp dir
      changed_when: false
      ansible.builtin.file:
        name: /tmp/nvim
        state: absent
...
